# CQ1: Competencias de um aprendiz especifico
# (Which specific competencies has a given learner demonstrated?)
PREFIX : <http://www.ontolearn.com/ontologia#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?compLabel WHERE {
  ?aprendiz a :Aprendiz ;
            rdfs:label "Joao Silva" .
  ?aprendiz :desempenhoCompetencias ?des .
  ?des :competenciaAvaliada ?comp .
  ?comp rdfs:label ?compLabel .
}
