# CQ4: Pre-requisitos transitivos (Diretos e Indiretos)
# (Direct and indirect prerequisites for a competency)
PREFIX : <http://www.ontolearn.com/ontologia#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?preReqLabel WHERE {
  ?comp rdfs:label "Heranca em Python" .
  # O operador '+' aciona a busca transitiva na propriedade
  ?comp :requer+ ?preReq .
  ?preReq rdfs:label ?preReqLabel .
}
